-- +++ UP Migration
CREATE TABLE farmers (
	user_id UUID PRIMARY KEY,
	phone_number VARCHAR(20),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- --- DOWN Migration
DROP TABLE IF EXISTS farmers;