
CREATE TABLE buyers (
	user_id UUID PRIMARY KEY,
	company_name VARCHAR(255) NOT NULL,
	contact_details TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- --- DOWN Migration
DROP TABLE IF EXISTS buyers;